version: 5.0.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        文章归档: /archives
        文章分类: /categories
        标签: /tags
        关于: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/gezhi-io/
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        知乎:
            icon: fab fa-zhihu
            url: https://www.zhihu.com/people/mathif
        
article:
    highlight:
        theme: atom-one-dark
        clipboard: true
        fold: ''
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
# comment:
#     type: ''
#     shortname: ''
donates:
    -
        type: alipay
        qrcode: '/img/alipay.png'
    -
        type: wechat
        qrcode: '/img/wechatpay.png'
    -
        type: buymeacoffee
        url: https://www.buymeacoffee.com/gezhi
# share:
#     type: ''
#     install_url: ''
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: 格致开物
        author_title: 数据分析、绘画
        location: 北京
        avatar: 
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/gezhi-io
        social_links:
            
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            我的B站空间: https://space.bilibili.com/43879650/
            数学建模百科: https://www.gezhi.wiki
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
